### ISSUE TITLE
Wrong domain?

### ISSUE THREAD

**Issue by TaiKamilla** [Adyen/adyen-shopware6#107]
**Describe the bug**
Looks like there is a call to a domain that does not exist
When trying to go live we get this error
![image](https://user-images.githubusercontent.com/15035750/102883109-be417c80-444f-11eb-9044-f0cbd049643a.png)

**Possible reason:**
Looks like this domain does not exist  `adyen-payments.com`

**Comment by acampos1916** [comment]
Hi @TaiKamilla,

Looks like the live endpoint configured has a `live_` prefix, this doesn't seem correct. See https://docs.adyen.com/plugins/shopware-6#set-up-shopware

> The URL prefix [random]-[company name] from your Adyen live Customer Area 

Is the correct live endpoint prefix being used?

Cheers,
Ángel
