### ISSUE TITLE
[PW-4158] Missing reverse side DAL definition for OrderTransaction for payment response

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#133]
**Describe the bug**
Missing reverse side on OrderTransaction for payment response. Just missing the corresponding EntityExtension.

**To Reproduce**
Execute `bin/console dal:validate` after installing plugin on Shopware 6.3.5.1

**Comment by peterojo** [comment]
Hi @AndreasA thanks for bringing this to our attention.

**Comment by AndreasA** [comment]
@peterojo any news regarding this, it is really simple to fix, just add a OrderTransactionExtension and the corresponding definition.

**Comment by peterojo** [comment]
Hi @AndreasA this is scheduled for next week

**Comment by AndreasA** [comment]
@peterojo Great. will this then result in a new released version 1.6.0 or 1.6.1 because it would then contain all the necessary changes and I could remove a lot of workarounds.
