### ISSUE TITLE
[PW-4180] Multi-Step / Custom checkouts (e.g. with headless) - Various issues

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#135]
**Describe the bug**
Not sure, if I have found them all yet but in one project, the checkout is setup like this:
- Step 1:  Enter shipping method and addresses
- Step 2: Select payment method
- Technicall still step 2 but only after the payment method has been selected: Enter payment details
- Step 3: Summary plus entering additional data (one is required)

This results in:
- The adyen payment data is deleted as soon as one enters data in step 3 as you clear the context on all context changes which can also just be a currency change: https://github.com/Adyen/adyen-shopware6/blob/1.5.0/src/Subscriber/PaymentSubscriber.php#L370
- Saving the adyen data requires the payment method ID to be sent with it. However, as mentioned above, this can be done in a separate request and then it does not make sense to sent it again: https://github.com/Adyen/adyen-shopware6/blob/1.5.0/src/Subscriber/PaymentSubscriber.php#L341

Possible solutions:
- Use payment method ID from context, if the parameter `paymentMethodId` has not been provided as that is the current valid payment method ID then as it didn't change.
- Clear the adyen payment only for some context changes, e.g. if the payment method changes. Probably the only one it should be cleared actually.
- Add a scheduled task (like you already did for other stuff) that periodically checks if there are old/expired entries and remove them to avoid old payment data from incomplete checkouts filling up the database table. Maybe in combination with the context lifetime parameter: https://github.com/shopware/platform/blob/v6.3.5.1/src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php#L35

**Comment by peterojo** [comment]
Hi @AndreasA, thanks for the suggestions. Indeed it does make sense to save/clear the payment state data only when the payment method is changed (i.e. when `paymentMethodId` exists in the request).
However, I don't think it is necessary to add a scheduled task, the `saveStateData` method reliably cleans up old data whenever the PM changes and the new PM has no state data. Please let us know if you encounter a bug/edge-case in which old state data remains in the DB

**Comment by AndreasA** [comment]
@peterojo 
with the change regarding payment method ID now the data will not be cleared that often anymore. also if someone stops the payment altogether I don't think it is cleared at all now?

also shouldn't you also call save Data, if adyenState has been transmited and not only if payment method id has been transmited?

**Comment by peterojo** [comment]
Hey @AndreasA you make a good point about the flow when someone abandons the cart altogether after selecting a payment method. I will make a follow up internal ticket to deal with this.
To your other point, we are accepting the state.data and `paymentMethodId` in the same request, this way we can better ensure that at most one state data record exists for the current context token, i.e. if the payment method changes, then we need to also remove the existing state data, if any, and/or save the current one.
There's also the possibility to send the state data directly with the payment request to `/handle-payment` without saving it in the database. See [here](https://github.com/Adyen/adyen-shopware6/blob/8e703f3285ad2a3921f81ec93d8b787cdd439481/src/Handlers/AbstractPaymentMethodHandler.php#L248), at the moment we use this for payment components with a direct pay button, like Google pay

**Comment by AndreasA** [comment]
@peterojo

What about:
- Step 1: Select payment method: credit card.
- Step 2: Enter payment details
- Step 3: Summary
- Step 4: Submit.

I really don't want to send the existing payment method Id again in this scenario. I would prefer to just send the payment details in this case.

**Comment by peterojo** [comment]
Hey @AndreasA,
It is possible to allow you to send the payment data as a separate request after selecting the payment method, we can get the saved payment method from the context.
What do you think of the following flow, when responding to the `SalesChannelContextSwitchEvent`:
if `paymentMethodId` exists:
    save / clear state data for current context
else if `adyenStateData` exists AND current selected PM is Adyen PM:
    save / clear state data for current context
else:
    do nothing

**Comment by AndreasA** [comment]
@peterojo 
I think that would work, maybe it could be simplified to something like this:
```php
    $paymentMethodId = $requestData->get('paymentMethodId');
    if (null !== $paymentMethodId) {
          // DELETE adyen payment data.
    }
    if (null !== $requestData->get('paymentMethodId') && $context->getPaymentMethod()->getId === $paymentMethodId) {
         // Save adyen data.
    }
```

**Comment by AndreasA** [comment]
@peterojo 
If you adjust to the change above,  you also need to add a fallback to the context's payment method Id here, if there was no paymentMethodId provided in the context:
https://github.com/Adyen/adyen-shopware6/blob/develop/src/Subscriber/PaymentSubscriber.php#L402

**Comment by peterojo** [comment]
@AndreasA great suggestion, I will only change one thing: if the paymentMethodId is provided, then delete the payment data.
Even if it is the same as the current selected one, because a user of the plugin (storefront) can decide to select the same payment method and change the card/issuer for example

**Comment by AndreasA** [comment]
@peterojo
Regarding deleting payment data upon using the same payment method ID, that is fine. 

However, that was way I added the the `null` option to explicitely delete the payment state data, so it does not happen unexpectely, e.g. if I just click on the same payment method.

Regarding `adyenStateData: null`: 
That is why I checked with `has` and not `get` because has is not the same as `get`.  
Has checks if the value was sent at all. It is NOT the same as using 😄 You can easily verify by debugging a switch context request.
`has` uses array_key_exists internally. That just check for the existence.

Regarding use case: we have a button on the payment form that is caleld update payment data, this basically deletes the existing data and refreshes the info, if payment data is stored, in a mobx store.

Especially, this ensures that if the user refreshes the page, the state does not switch to payment data has already been entered.

Currently I actually do this by sending the same payment method ID again which deletes the data but I think that is a bit hacky and I would prefer to do this cleaner.

**Comment by peterojo** [comment]
@AndreasA in the storefront plugin we are always sending the `adyenStateData` field in the form for selecting a payment method. For the payment methods without state data, the `adyenStateData` will be empty, that is why we are using `$event->getRequestDataBag()->get('adyenStateData')` to check for state data. If we use `$event->getRequestDataBag()->has('adyenStateData')` it will always be true.
For your use case, what do you think about if we create an API endpoint for this, instead of hooking that into the `SalesChannelContextSwitchEvent` event?

**Comment by AndreasA** [comment]
@peterojo Separate API request is fine too. So you can keep using `get` here.

**Comment by peterojo** [comment]
Great! I created an internal ticket for the new API endpoint.

**Comment by AndreasA** [comment]
@peterojo Just noticed that the paymentMethodId validation should actually be removed as you now fallback to the default payment method in case non was provided. Which is what might be needed as dicussed above for multi-step / PWA setups. So the validation, is probably wrong.

If you want to add a check regarding invalid payment method, you could add it as `else` to the condition `if ($paymentMethod->getPluginId() === $this->adyenPluginId) {`

**Comment by AndreasA** [comment]
@peterojo Just to let you know, I did the update to 1.6.0 today and it works great. I was able to remove a lot of workarounds for these things. Thanks.

**Comment by peterojo** [comment]
@AndreasA thanks for the feedback :)
