### ISSUE TITLE
Redirect after payment not to checkout/finish, but to startpage instead

### ISSUE THREAD

**Issue by wolv-dev** [Adyen/adyen-shopware6#144]
**Describe the bug**
This problem occurs only on shops, that have another domain configured in saleschannel.
For example, the configured domain in saleschannel ist not `example.com`, but `example.com/en`.

**To Reproduce**
1. Log in to administration backend, and go to saleschannels
2. Scroll down to domains and change your existing domain to `example.com/en`.
3. Save the settings and visit the frontend. Check if address is `example.com/en`.
4. Buy a item and finish the checkout.
5. When `example.com/adyen/redirect-result` will be called, the shop is redirecting to `example.com/en`.

**Expected behavior**
On 5. it should redirect to `example.com/en/adyen/redirect-result` and than correctly to checkout/finish page.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Chrome, Firefox
 - Latest Versions

**Additional context**

**Comment by acampos1916** [comment]
Hi @wolv-dev, thanks for opening this issue.

Sounds a lot like #136 which is already being fixed by #137. Could you check if this solves it for you as well?

Ángel

**Comment by wolv-dev** [comment]
@acampos1916 Yes, this solves the problem. When will be the update available in showpare store?

**Comment by acampos1916** [comment]
@wolv-dev awesome. I'll close the issue now that the PR is merged.

The next release is scheduled in about 1-2 weeks, it will also be available in the Shopware store.

**Comment by wolv-dev** [comment]
I updated to version 1.6.0 and debugged the `$adyenReturnUrl`:
`https://example.com/adyen/redirect-result?_csrf_token=x0KKgV_WhH2DC_00whGZi7VfT2FzeKNIUXSAiddvgXk`

But it should be `https://example.com/en/adyen/redirect-result`

I don't know, why it worked when I changed it manually in code, but now it doesn't.
I deleted/cleared cache, rebuilt theme, regenerated SEO URLs.
