### ISSUE TITLE
Additional info regarding meeting today - failed payments - default handling testing

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#150]
Hi,

I was not sure how to best let you know about this, so I just added an issue here.

I forgot to mention this during our meeting today but in the project I showed you, we use non default payment error handling:
- In that project we restore the cart upon order creation.
- And delete that cart if the payment was successful.

This allowed us to just return to the payment method step of the checkout upon payment errors and the user could leave the payment process but still continue with the order.

However, in a default checkout this is a bit differnt, upon failed payment the following could be done:
- Repay
- Change payment method and repay.

This should also be testet, if it works correctly with PWAs.
It should work fine as that is default Shopware behavior and functionality but as mentioned: In the project I showed, it is handled differently, so you probably should at least verify it works also with the default behavior.

**Comment by peterojo** [comment]
Hi @AndreasA thanks for noting this. We expect however that PWA clients would be free to manage the cart and the order anyway they want just by using the store API. Most important from our perspective is that we allow PWA clients to send the payment state data and successfully make payment with Adyen.

**Comment by AndreasA** [comment]
@peterojo Great just wanted to let you know. it will probably work fine though I guess as this should be Shopware default handling.
