### ISSUE TITLE
Extend shopware payment method entity to include adyen paymentmethods data.

### ISSUE THREAD

**Issue by peterojo** [Adyen/adyen-shopware6#154]
**Headless integrations have to add workaround for getting /paymentMethods data**
With headless integrations such as PWAs it would be useful to extend each Adyen payment method entity to include the corresponding data from the `/paymentMethods` API response from adyen as well as fields like `useAdyen: true`, and `type:scheme`

**Proposed solution**
Create entity extension for PaymentMethodEntity and add new fields for `usesAdyen`, `type` as well as json field for the filtered `/paymentMethods` data for each PM.
Listen for requests to `/store-api/v*/payment-method` and update all adyen PMs with the latest data from the API
Find a way to include adyen info in the `/store-api/v*/payment-method` API response 

**Alternative solution**
Another solution would be to periodically update the payment method entities via a cronjob instead of listening for payment-method requests

**Comment by peterojo** [comment]
@AndreasA I wonder if you have any ideas about implementing such a solution

**Comment by AndreasA** [comment]
@peterojo One solution would be to use the event 'sales_channel.' . PaymentEvents::PAYMENT_METHOD_LOADED_EVENT

this would allow you to add data on the fly to the payment method response, if it uses the sales channel repository.

Maybe you also need to do so without sales channel and check if you are in the store-api etc. otherwise but I think it should be enough for the sales channel.

you will need an entity extension with a runtime computed field too.

**Comment by AndreasA** [comment]
@peterojo Alternative, in this case it might be better as the payment method response is only required for this one API:

- Create a Response subscriber.
- Ensure it is executed before `\Shopware\Core\System\SalesChannel\Api\StoreApiResponseListener`
- Check if the response is `instanceof PaymentMethodRouteResponse`
- Maybe also check the `route` used is `store-api.payment.method` but with the `instanceof` check it is not necessary
- Add extension to payment methods in the `PaymentMethodRouteResponse`.

**Comment by AndreasA** [comment]
@peterojo I hope I will be able to do create PRs this or next week. At least currently it looks good that I will get the time.

**Comment by peterojo** [comment]
@AndreasA that would be great, we have also scheduled this ticket for this or next week so I will definitely allocate some time. Please go ahead and make a PR whenever you can and I will take a look.

**Comment by AndreasA** [comment]
@peterojo One question: I should probably also limit the available payment methods here, correct?

Furthermore, I have been wondering this for some time but why do I need to add the whole payment methods response to the called component, shouldn't it jut be the one for the current type?

**Comment by peterojo** [comment]
> @peterojo One question: I should probably also limit the available payment methods here, correct?
> 
> Furthermore, I have been wondering this for some time but why do I need to add the whole payment methods response to the called component, shouldn't it jut be the one for the current type?

@AndreasA Yes it should only be one payment method type that should be added to each PaymentMethodEntity through extension, not the entire /paymentMethods response. You would need to somehow filter the `/paymentMethods` response and separate each PM so that you can add it to it corresponding entity

**Comment by AndreasA** [comment]
@peterojo OK. thanks. that will work.

I started with the implementation today.

btw. what was the second PR you wanted me to create ?

**Comment by peterojo** [comment]
> btw. what was the second PR you wanted me to create ?

None that I can think of for now, thanks :)

**Comment by AndreasA** [comment]
@peterojo I just rembered the other one was to extend the context to add the adyen client key to it, so it can be used by the PWA. I hope to have both ready at the beginning of next week.

**Comment by AndreasA** [comment]
@peterojo  Just created the PR https://github.com/Adyen/adyen-shopware6/pull/162

Please also test as I only have credit card available in the sandbox, so I could net check that it works correclty if there are multiple methods.

**Comment by AndreasA** [comment]
@peterojo I also created the second one regarding client Key and environment: https://github.com/Adyen/adyen-shopware6/pull/163/files

**Comment by AndreasA** [comment]
One more helpful thing might be to add an info to the order if an adyen payment was used because only in that case the adyen payment status has to be retrieved.

However, if I have the payment methods stored locally I can determine this information by checking the order transactions payment method ID, so it is not strictly needed as that allows one to determine this information anyway.

But it could be done by using `Shopware\Core\Checkout\Order\OrderEvents::ORDER_LOADED_EVENT` event subscriber and adding information to the order according to its transactions.

**Comment by peterojo** [comment]
@AndreasA thanks for the PRs, indeed we already use the payment method from the latest transaction to determine if an order was paid through Adyen, for now I don't think we need to add that to the order.
Later we will add the notification info to the order details page in the admin based on the notifications

**Comment by AndreasA** [comment]
@peterojo It would just make it easier to determine in a PWA without requiring too much logic but retrieving the last transactions payment method and checking if it was an adyen payment method should be simple enough :smile:
