### ISSUE TITLE
[PW-4474] Payment Refund 

### ISSUE THREAD

**Issue by kamelz** [Adyen/adyen-shopware6#157]
**Is your feature request related to a problem? Please describe.**
Whenever we refund a user from Adyen admin panel and the status doesn't change on Shopware backend.

**Describe the solution you'd like**
- We want to be able to make an order refund from Shopware backend by changing the order status.
- If we refunded a payment from Adyen admin panel the order status is updated at Shopware backend.

**Comment by peterojo** [comment]
Hi @kamelz thanks for creating the issue, we've created an internal ticket to implement refunds in the plugin.

**Comment by peterojo** [comment]
#161 will process REFUND notifications and update transaction states in Shopware if a refund is made from Adyen CA.
It does *not* add support for requesting refunds directly from the Shopware administration (this is a more extensive feature addition and we will add this in the future).
