### ISSUE TITLE
[PW-4704] LineItem description ist not set on inherited variant name

### ISSUE THREAD

**Issue by Gugiman** [Adyen/adyen-shopware6#167]
**Describe the bug**
LineItem description ist not set on inherited variant name.
Therefore the payment request fails.

**To Reproduce**
1: Create an article and within variants with inherited name
2: Order the item
3: $lineItem['description'] is empty
4: Request fails and tells that InvoiceLines are missing (also wrong)

**Expected behavior**
Get the name ob the base article when imherited

**Comment by peterojo** [comment]
Hi @Gugiman thanks for reporting this issue. We will investigate this as soon as possible.
