### ISSUE TITLE
Guest orders through saleschannel api do not have the addresses set on the saleschannelcontext

### ISSUE THREAD

**Issue by jurriaanr** [Adyen/adyen-shopware6#182]
**Describe the bug**
When we create a (headless) guest order through the saleschannel api we receive this error:

Line 401 of vendor/adyen/adyen-shopware6/src/Handlers/AbstractPaymentMethodHandler.php it tries to get this object: `$salesChannelContext->getShippingLocation()->getAddress()->getCountryState()` but `getAddress()` is null

This will produce an exception with message: Call to a member function getCountryState() on null

This is probably because the context is recreated on a guest order so it misses those addresses, but also f.e. the customer. 
Why is the context expected to have this information? Is this expected to have that information? We noticed other payment methods using the order to get this information from.

**To Reproduce**
1. create a headless guest order
```
POST {{host}}/sales-channel-api/v3/checkout/guest-order
sw-access-key: {{swApiKey}}
sw-context-token: {{swContextToken}}
Accept: */*
Content-Type: application/json

{
    "billingAddress": {
        "street": "BillingStreet 1",
        "city": "City",
        "zipcode": "T11 A11",
        "countryId": "someid",
        "firstName": "First Name Billing",
        "lastName": "Last Name Billing",
        "salutationId": "someid",
        "additionalAddressLine1": ""
    },
    "shippingAddress": {
        "street": "shipping street 1",
        "zipcode": "T11 A11",
        "city": "City",
        "countryId": "someid",
        "firstName": "First Name Shipping",
        "lastName": "Last Name Shipping",
        "salutationId": "someid",
        "additionalAddressLine1": ""
    },
    "storefrontUrl": "https://someurl,
    "firstName": "Firstname Customer",
    "lastName": "Lastname Customer",
    "email": "test@test.test",
    "salutationId": "someid"
}
```
and than pay the order

```POST {{host}}/sales-channel-api/v3/checkout/order/{{orderId}}/pay
sw-access-key: {{swApiKey}}
sw-context-token: {{swContextToken}}
Accept: */*
Content-Type: application/json

{
    "finishUrl": "https://someurl"
}
```

**Expected behavior**
Init the order process and get redirect url

**Comment by peterojo** [comment]
Hi @jurriaanr, thanks for opening this issue! May I ask which version of the plugin and which version of Shopware you are using?
I notice that you are still using the Sales Channel API which is marked as deprecated and removed in v6.4
From version 1.5.0 of this plugin, our implementation has been based on the Store API.
Please consider using the `/store-api/v3/checkout/order` (or `/store-api/checkout/order` in Shopware 6.4) instead of `sales-channel-api/v3/checkout/guest-order`

**Comment by peterojo** [comment]
Hi @jurriaanr if you are on v1.4 or lower and you cannot upgrade, please let us know which versions you are using so that we can look into reproducing the bug. Thanks

**Comment by AndreasA** [comment]
Hi @jurriaanr the sales channel API has actually been deprecated and I think with 6.4 it should even have been removed. So you should not use it anymore.

If I understand it correctly now the expected way to create a guest order now is to:

- Create a guest customer (using the registration API with the corresponding flag): https://shopware.stoplight.io/docs/store-api/storeapi.json/paths/~1account~1register/post
- Create a normal order https://shopware.stoplight.io/docs/store-api/storeapi.json/paths/~1checkout~1order/post

**Comment by jurriaanr** [comment]
We are using version 2.0 of the plugin and version 6.3.5.4 of Shopware. I am aware that the saleschannel api is deprecated starting Shopware 6.4 however in 6.3 it is not, and since v2 of the plugin does not support 6.4 yet I was hoping for saleschannel support as well, but I understand the decision. Unfortunately changing the api on a big project is not as easy to do between other ongoing development, but going forward we will have to anyway.

**Comment by AndreasA** [comment]
The API is already deprecated with 6.3.5.4 but not yet removed. I think with 6.4 it was removed.

And I agree with you that changing APIs is not that easy but in that regard I think the issue is that Shopware decided to remove an API that has been newly introduced with 6.x and replace it with a different API. Personally, I don't understand that decision.

But you are correct it should probably also work for this API.

@jurriaanr Have you checked you call the pay URL with the new context token that the guest order URL provides? Because if I remember correctly, the context token changes here and the new context contains the guest customer which the old one does not.

**Comment by AndreasA** [comment]
@jurriaanr Just to exclude this as an issue: 
Have you checked you call the pay URL with the new context token that the guest order URL provides? 
Because if I remember correctly, the context token changes here and the new context contains the guest customer which the old one does not.

**Comment by dfanica** [comment]
The main reason in using the plugin was to get access to the Oney payment method which we found that will not be available before version 3.0 making the upgrade a requirement since the new version is not backwards compatible either.

**Comment by jurriaanr** [comment]
You are correct, it was already deprecated, I meant removed indeed. I also agree I do not understand the move of Shopware :) I do not think we use the new context provided by the guest order. It is indeed renewed there, however (I did not check this in 6.3) but in 6.2 it would be recreated with an incorrect shipping method (it sets the default shipping method of the saleschannel on the context, instead of the one the user selected). Anyway, as colleague above mentions, we decided we will not be able to use the plugin anyway until we upgraded to 6.4. So I will close the issue for now, since yes.. it is probably to much effort to support the saleschannel api in v2 of the plugin

**Comment by AndreasA** [comment]
If I remember correctly, after a register the context token changes, the new one is provided in the response and has to be used for furhter calls.
in case you crated a context token before calling register, this might be the reason why (though not 100% sure)

**Comment by MohamadAlalwan** [comment]
> If I remember correctly, after a register the context token changes, the new one is provided in the response and has to be used for furhter calls. in case you created a context token before calling register, this might be the reason why (though not 100% sure)

As pre their documentation, they won't share new context token, and if use the same token you pass on registeration, still not working

https://shopware.stoplight.io/docs/store-api/b08a8858e0c5d-register-a-customer

**Comment by AndreasA** [comment]
@MohamadAlalwan It is not shown in the API documentaiton but it is should be part of the response headers. not the json. but the headers.
