### ISSUE TITLE
[PW-8389] Set oneclick as default customer payment method after saving card details

### ISSUE THREAD

**Issue by peterojo** [Adyen/adyen-shopware6#188]
When a shopper selects card payment and checks the box to 'save for next use', we store the payment method in checkout, but the next time the shopper goes to checkout, the previously used PM (i.e. credit card) is pre-selected instead.
It would be an improvement to pre-select oneclick after customer pays with and saves credit card.

**Comment by adyen-integrations-support** [comment]
Hi Peterojo,

Thank you for your suggestion. We appreciate your feedback and understand the value this feature could add.

Currently, this functionality isn’t on our development roadmap and is not expected to be implemented in the near future, as it depends on Adyen’s feature planning and prioritization. However, we’ll certainly take it into consideration for future updates.

We’ll keep you informed if this option becomes available.

Best regards

**Comment by adyen-integrations-support** [comment]
Hi,

Sorry for the confusion. This functionality has already been implemented in the Adyen plugin.

To allow customers to store their card details for future transactions, please enable the "Stored Payment Methods | Adyen Payment" option. This requires that both "Stored Payment Methods | Adyen Payment" and "Cards | Adyen Payment" are enabled, allowing customers to save their card information. This is only working for registered users.

Could you please let us know if this resolves your issue?

Thank you in advance for your response.

Best regards
