### ISSUE TITLE
Add the Apple Pay express checkout option

### ISSUE THREAD

**Issue by ghost** [Adyen/adyen-shopware6#194]

**Comment by adyen-integrations-support** [comment]
Hi Andreas,

Thank you for your suggestion to add Apple Pay Express Checkout to the plugin. We appreciate your input, as it helps us understand the features that matter most to you.

At this time, however, this enhancement is not scheduled, and it is not anticipated in the near future. Implementation would depend on the Adyen team’s roadmap and priorities.

We’ll be sure to share any updates on feature developments that could support your request.

Best regards
