### ISSUE TITLE
[PW-6014] Missing `refusalReasonCode` and `refusalReason` from payment-status store API response

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#209]
**Describe the bug**

See: https://github.com/Adyen/adyen-shopware6/blob/develop/src/Handlers/PaymentResponseHandler.php#L299

where for authorized, refused and errors, only the resultCode is provided but not refusal reason or code.

However, in order to provide the user with error codes related to the refusal reason, it is necessary to have this information in a PWA.

**Comment by AndreasA** [comment]
@peterojo just to let you know I recently did an upgrade on the headless project adyen is in use and except for a workaround for this fix, the default adyen implementation works there (except for the 3DS secure v1 redirect storefront is enabled on the sales channel, but that was more an issue with Shopware - might be fixed now but didn't test it).

**Comment by AndreasA** [comment]
@peterojo Any news regarding this ?

**Comment by peterojo** [comment]
Hi @AndreasA this has been added in #236, pending the next release.

**Comment by AndreasA** [comment]
@peterojo One more question i noticed that some refusal codes like `22` with message `FRAUD-CANCELLED` is returned as `Cancelled` by Adyen itself instead of refused.

In this case with the change from https://github.com/Adyen/adyen-shopware6/pull/236 will not be shown as cancelled uses the default refusal code.

Also `Authorised` according to https://github.com/Adyen/adyen-shopware6/pull/236/files returns also refusal codes which seems wrong.

maybe move authorised outside and add canceled to the error/refused block ?

**Comment by RokPopov** [comment]
Hey @AndreasA could you please try this PR -> https://github.com/Adyen/adyen-shopware6/pull/240 and see if it solves the issue for you?

**Comment by RokPopov** [comment]
Hi @AndreasA , thanks for the testing this and updating us. Happy to see the correct response is being shown.
