### ISSUE TITLE
dal:validate errors due to missing version reference foreign columns.

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#220]
**Describe the bug**
When executing dal:validate with Shopware 6.4.7.0 and the plugin in version 3.2.0 I get the following errors:

```shell
=========================================
Adyen\Shopware\Entity\PaymentResponse\PaymentResponseEntityDefinition
---------------------------------------------------------------------
 * Missing version reference for foreign key column order_transaction.id for definition association adyen_payment_response.orderTransaction
Adyen\Shopware\Entity\Refund\RefundEntityDefinition
---------------------------------------------------
 * Missing reverse one to many association for Adyen\Shopware\Entity\Refund\RefundEntityDefinition <-> Shopware\Core\Checkout\Order\Aggregate\OrderTransaction\OrderTransactionDefinition (orderTransaction)
 * Missing version reference for foreign key column order_transaction.id for definition association adyen_refund.orderTransaction
```

**Versions**
Shopware version: 6.4.7.0
Plugin version: 3.2.0

**To Reproduce**
1. Install a new Shopware instance (blank).
2. Add Adyen plugin (e.g. using composer).
3. Install and activate aAdyen plugin.
2. Executed bin/console dal:validate

**Expected behavior**
No error to occur.

**Comment by adyen-integrations-support** [comment]
Hi @AndreasA ,

Thank you for your patience while we worked on resolving the issue. We want to let you know that the problem has been fixed and the solution will be included in the next version of the plugin.

Best regards
