### ISSUE TITLE
Call to undefined method getShopwareVersion() StoreService

### ISSUE THREAD

**Issue by erwinn** [Adyen/adyen-shopware6#231]
**Describe the bug**
Since new Shopware version, we receive this error in the checkout:
`Attempted to call an undefined method named "getShopwareVersion" of class "ContainerKsnNhda\StoreService_93b91c4`
`src/Service/ClientService.php:113`

**Versions**
Shopware version: 6.4.8.1
Plugin version: 3.3.0

**To Reproduce**
1. Put items in basket
2. Go to checkout/confirm page in SW
3. You'll receive an 500 error, see error log

**Expected behavior**
Would expect no error

**Screenshots**
![image](https://user-images.githubusercontent.com/10939597/153913702-c3d3f546-537c-4a6d-b074-198ba5de4c46.png)

**Comment by Morerice** [comment]
Hi @erwinn,

Thanks for opening this issue. It has been fixed on v3.3.1.

Best regards,
Jean
Adyen
