### ISSUE TITLE
House number is display as N/A

### ISSUE THREAD

**Issue by mastox** [Adyen/adyen-shopware6#245]
**Describe the bug**
PayPal shows N/A on the address line, because you don't split the house number from the address line.
https://github.com/Adyen/adyen-shopware6/blob/7e9427e70fb857dda8fead1729c93e6e6cf63316/src/Handlers/AbstractPaymentMethodHandler.php#L352

**Versions**
Shopware version: v6.4.9.0 Stable Version 
Plugin version: Version: 3.3.1

**To Reproduce**
Pay with PayPal 

**Expected behavior**
House number should be split from the address line and should display correct on any payment, and in Adyen backend.

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any
 - Version any

**Comment by peterojo** [comment]
This issue is resolved in #255 and will be released in version 3.5
