### ISSUE TITLE
Plugin update fails due to composer restraints

### ISSUE THREAD

**Issue by mm-mereien** [Adyen/adyen-shopware6#250]
**Describe the bug**
When trying to update the plugin via the shopware backend, there is an error message: 
Required plugin/package "monolog/monolog ^1.16" does not match installed version == 2.4.0.0.

**Versions**
Shopware version: 6.4.9.0
Plugin version: 3.3.1

**To Reproduce**
1. Go to installed plugins
2. Click "update" for the Adyen Payments für Shopware 6 plugin

**Expected behavior**
The plugin updates without an error

**Screenshots**
![grafik](https://user-images.githubusercontent.com/104507590/165525706-f7f0f787-7b76-4120-8b0a-996cfe981aef.png)

**Additional context**
When manually changing the monolog version in the composer.json back to "^2" from "^1.16" the plugin update can be done via console.
Commit that does change the version constraint: 9e9e9e34cea39e33b79f6218044ab0b3a2cb28e6

**Comment by peterojo** [comment]
Hello @mm-mereien thanks for reporting this issue. We're are working on fixing this ASAP

**Comment by peterojo** [comment]
The plugin has been updated on the marketplace, please try again

**Comment by mm-mereien** [comment]
Hello @peterojo , Plugin update via backend is succesfull again, thank you
