### ISSUE TITLE
Test Configuration Button Always uses Test API Key, even if Live Environment is activated

### ISSUE THREAD

**Issue by Watschman** [Adyen/adyen-shopware6#256]
**Describe the bug**
Test Configuration Button in Admin backend always uses Test API Key, even if the Live Environment is activated.

**Versions**
Shopware version: [e.g. 6.4.11.1]
Plugin version: [e.g. 3.4.1]

**To Reproduce**
1. Go to the Admin Backend and into die Adyen Payments Configuration
2. Enter Valid Live API Key, Valid Merchant Account, valid live endpoint URL prefix and activate Live Environment toggle
3. Click on 'Test Configuration' Button
5. See error 'Unauthorised'

**Expected behavior**
I expected a success message

**Screenshots**
I think a description is plentiful in this case

**Desktop (please complete the following information):**
 - OS: [Tested on Linux CentOs 7, Linux CentOs 8, Windows 10 and Windows 11 and Mac OSX]
 - Browser [Tested in Chrome, Firefox, Safari and Microsoft Edge]
 - Version [Current Versions]

**Smartphone (please complete the following information):**
 No Smartphone was tested

**Additional context**
Just took me almost an entire work day to figure out why the plugin kept responding with Unauthorized. So I backtracked the requests, to find out that your plugin always uses the Test API Key, regardless of Environment configuration.
It is an easy, I would have created a Pull Request, but I am not that familiar with Github, so I didn't bother.

Steps to fix:
https://github.com/Adyen/adyen-shopware6/blob/33d2d0dde3db02a75f222a68d202565faab28cd5/src/Controller/AdminController.php#L136

Change `$client->setXApiKey($dataBag->get(ConfigurationService::BUNDLE_NAME . '.config.apiKeyTest'));`
To: `$client->setXApiKey($dataBag->get(ConfigurationService::BUNDLE_NAME . '.config.environment') ? ($dataBag->get(ConfigurationService::BUNDLE_NAME . '.config.apiKeyLive')) : ($dataBag->get(ConfigurationService::BUNDLE_NAME . '.config.apiKeyTest')));`

**Comment by peterojo** [comment]
Hi @Watschman thanks for spotting this! It is indeed a very easy fix, we will work on it
