### ISSUE TITLE
[PW-8365] format() on null for getUpdatedAt() in AdminController

### ISSUE THREAD

**Issue by dude2511** [Adyen/adyen-shopware6#270]
**Describe the bug**
I get `"Call to a member function format() on null` in the logs for AdminController:356 (using plugin version 3.4.1 in live mode). I guess, if updatedAt is null, there is no date object and hence no `format()`, but I did not further investigate.

**Versions**
Shopware version: [e.g. 6.4.12.0]
Plugin version: [e.g. 3.4.1]

**Comment by candemiralp** [comment]
Hello @dude2511,

Thank you for raising this issue. We reproduced the issue and an implementation ticket was created.

Best Regards,
Can

**Comment by timkoopmans50** [comment]
Also an issue on 3.10.1 and probably 3.11.0. What's the ETA for a fix on this? My client has issues with this now.

**Comment by dude2511** [comment]
@timkoopmans50 
I added a patch file to our deployment script fixing the issue in the meantime. You need to verify that it works for your plugin version and adapt it otherwise.

```
--- AdminController.php	2022-11-23 01:36:06
+++ edit/AdminController.php	2022-11-23 01:38:15
@@ -356,7 +356,7 @@
                     ? NotificationEntity::NOTIFICATION_STATUS_PROCESSED
                     : NotificationEntity::NOTIFICATION_STATUS_PENDING,
                 'createdAt' => $notification->getCreatedAt()->format(self::ADMIN_DATETIME_FORMAT),
-                'updatedAt' => $notification->getUpdatedAt()->format(self::ADMIN_DATETIME_FORMAT),
+                'updatedAt' => $notification->getUpdatedAt() ? $notification->getUpdatedAt()->format(self::ADMIN_DATETIME_FORMAT) : null,
                 'notificationId' => $notification->getId(),
                 'canBeRescheduled' => $this->notificationService->canBeRescheduled($notification),
                 'errorCount' => $notification->getErrorCount(),
`
``

**Comment by candemiralp** [comment]
Hello @dude2511,

Thank you for the patch. It will be released on the next version.

@timkoopmans50 you can use this patch if you don't want to wait for the next release and the situation is urgent for you.

Best Regards,
Can
