### ISSUE TITLE
Splitting of street and house number if a suite number is included

### ISSUE THREAD

**Issue by edip123** [Adyen/adyen-shopware6#308]
**Describe the bug**
Shopware doesn't have a separate field for house number and/or a suite number. A customer could enter it like this:
106-19 Dallas Road

The Adyen plugin splits it by looking for digits, but here a "-" is included, which causes the RegEx to fail, and no house number is sent to Adyen. This leads to a payment error, because address can't be checked.

**Versions**
Shopware version: all
Plugin version: all

**To Reproduce**
Just enter "106-19 Dallas Road" or something similar in the street field.

**Expected behavior**
The house number should be split from the street even if it includes a "-".

**Comment by edip123** [comment]
Seems Adyen developers are not interested in fixing problems.
This RegEx's in getSplitStreetAddressHouseNumber would fix the problem:
```
    $streetFirstRegex = '/(?<streetName>[\w\W]+)\s+(?<houseNumber>\d{1,10}((\s)?\w{1,3})?)$/m';
    $numberFirstRegex = '/^(?<houseNumber>\d{1,10}((\s)?\w{1,3})?)\s+(?<streetName>[\w\W]+)/m';
```

**Comment by peterojo** [comment]
Hi @edip123! Thanks for opening this issue. 
We're working on increasing our capacity to respond quicker to issues, but we also welcome and highly appreciate contributions via PRs. It would speed things up if you could kindly open a PR with your proposed solution so that we can review and test the changes.
Thanks!

**Comment by edip123** [comment]
Hi @peterojo 
i created PR 3 weeks ago, but it needs to be reviewed and merged by you...
