### ISSUE TITLE
[PW-7512] 1st failed payment overwrites 2nd successful payment

### ISSUE THREAD

**Issue by cyborgii** [Adyen/adyen-shopware6#311]
**Describe the bug**
1st failed payment overwrites 2nd successful payment

**Versions**
Shopware version: 6.4.13
Plugin version: 3.7.1

**To Reproduce**
1. Make payment via MC or Visa
2. Payment must fail
3. Start second payment via e.g Klarna
4. Payment status changes to authorized
5. About 30 minutes later, the webhook messages of the failed payment is processed.
6. The Payment status changes to failed

**Expected behavior**
The 1st failed payment not to overwrite, the second succeeded payment

**Screenshots**
The red marked status changes is triggered by the messages sent via webhook.
![15-11-2022_15-39-45](https://user-images.githubusercontent.com/247184/201947670-547a08b2-2a20-4531-836d-3660a5e7f22c.png)

**Comment by peterojo** [comment]
Hi @cyborgii , thanks for raising this issue. We will investigate and release a fix ASAP
