### ISSUE TITLE
[PW-7807] Shopware affiliate marketing still not working

### ISSUE THREAD

**Issue by andydandy80** [Adyen/adyen-shopware6#334]
Regarding to #295 Shopware affiliate marketing is still not working.
I installed the plugin update 3.8.1 (Shopware Version 6.4.18.0) and made several tests afterwards. In no case the Affiliate-Code was saved. Whats going wrong?
With shopware own PayPal Plugin its working.

**Comment by candemiralp** [comment]
Hello @andydandy80,

Thank you for opening this issue again. We will inform you after completing our investigation. 

Best Regards,
Can

**Comment by candemiralp** [comment]
Hello @andydandy80,

I am closing this ticket for inactivity. If the proposed solution in the previous issue doesn't solve the issue, please re-open this issue.

Best Regards,
Can
