### ISSUE TITLE
[PW-7981] 500 error with Klarna afterpay Payment - not working

### ISSUE THREAD

**Issue by bitfactory-michel-lubbers** [Adyen/adyen-shopware6#344]
**Describe the bug**
When i want to pay with Klarna afterpay it triggers the following error:
[vendor/adyen/adyen-shopware6/src/Handlers/AbstractPaymentMethodHandler.php ](line 593)

```
if (!is_null($product->getSeoUrls())) {  
                 $hostname = $salesChannelContext->getSalesChannel()->getDomains()->first()->getUrl(); 
                 $productPath = $product->getSeoUrls()->first()->getPathInfo(); 
                 $productUrl = str_replace('//', '/', $hostname . $productPath); 
} else { 
                   $productUrl = null;                
}
```

**Versions**
Shopware version: 6.4.18.1
Plugin version: 3.8.1

**To Reproduce**
[Video because the url is behind private environment](https://user-images.githubusercontent.com/100353261/215312688-1cb080eb-3a42-4fb0-a95a-0404913d611a.webm)

1. Go to  a product
2. Add product to cart
3. Login or create account
4. Scroll down to payment
5. Choose Klarna payment
6. Click on Create Order
7. In the network tab you get a 500 error

**Expected behavior**
I expect to go to the payment portal of Adyen to finish the payment.

**Screenshots**
<img width="903" alt="Screenshot 2023-01-29 at 08 35 31" src="https://user-images.githubusercontent.com/100353261/215312259-95d90d30-1e1c-4b92-b528-8402822aedb6.png">
<img width="907" alt="Screenshot 2023-01-29 at 08 35 56" src="https://user-images.githubusercontent.com/100353261/215312273-daad6c68-d36f-4275-be1a-ef99edff7a28.png">

**Desktop (please complete the following information):**
 - OS: Ventura 13.2
 - Browser: Chrome
 - Version 109

**Additional context**
I found out that the following returns a empty array
`$product->getSeoUrls()`
this means that `$product->getSeoUrls()->first()` is NULL and `$product->getSeoUrls()->first()->getPathInfo()` will trigger the 500 error

To me it looks like that this `if (!is_null($product->getSeoUrls())) {  ` should be something like this `if (!is_null($product->getSeoUrls()) || !empty($product->getSeoUrls())) {  `

Ps. this is a variant product

**Comment by candemiralp** [comment]
Hello @bitfactory-michel-lubbers,

Thank you for creating this issue. We created an internal ticket for the solution.

Best Regards,
Can
