### ISSUE TITLE
[PW-7980] MerchantReference can be NULL for notifications

### ISSUE THREAD

**Issue by MelvinAchterhuis** [Adyen/adyen-shopware6#345]
**Describe the bug**
Somehow it is possible for a notification to have a NULL value for merchant_reference. This causes the notification scheduled task to complete break and don't run at all which results in non-updated payment status.

**Versions**
Shopware version: 6.4.17.2
Plugin version: 3.9.0

**To Reproduce**
Unknown why the notification doesn't have a merchant_reference, but if it happens the following error gets thrown when the scheduled task runs:

```
{
  "code": "0",
  "status": "500",
  "title": "Internal Server Error",
  "detail": "Adyen\\Shopware\\Entity\\Notification\\NotificationEntity::getMerchantReference(): Return value must be of type string, null returned"
}
```

**Expected behavior**
Scheduled task runs without error thrown, now it completely fails for all notifications that needs to be processed. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
src/Entity/Notification/NotificationEntityDefinition.php needs to be refactored, and database migrations needs to be adjusted. Now only ID is a required field but clearly that is not the case here. 

Also notifications that are currently in the database and that don't have a merchant reference shouldn't break the scheduled task, but the error should be catched.

**Comment by candemiralp** [comment]
Hello @MelvinAchterhuis,

Thank you for raising this issue. We created an internal investigation ticket for this one. We will inform you when we are done with the investigation about the possible solution.

Best Regards,
Can
