### ISSUE TITLE
[PW-8369] Type mismatch between NotificationEntity and ProcessNotificationHandler::markAsProcessing()

### ISSUE THREAD

**Issue by timkoopmans50** [Adyen/adyen-shopware6#376]
**Describe the bug**
Type error.

**Versions**
Shopware version: 6.4.17.2
Plugin version: 3.11.0

**To Reproduce**
1. Create a situation where the $merchantReference will be null. 
2. Task will now fail on a typerror.

**Expected behavior**
The merchantReference should either be nullable throughout the whole application or always be a string. 

**CODE SNIPPETS:**

This : 
https://github.com/Adyen/adyen-shopware6/blob/3.11.0/src/Entity/Notification/NotificationEntity.php#L51
https://github.com/Adyen/adyen-shopware6/blob/3.11.0/src/Entity/Notification/NotificationEntity.php#L153

Does not match types with this: (NULL would result in type error)
https://github.com/Adyen/adyen-shopware6/blob/3.11.0/src/ScheduledTask/ProcessNotificationsHandler.php#L382

**Comment by timkoopmans50** [comment]
Please note that if you encounter this condition your whole task manager will not function anymore, which for big webshops results in major financial damage.

**Comment by candemiralp** [comment]
Hello @timkoopmans50,

Thank you for raising this issue. You are right, that `TypeError` most probably won't be caught. We created an internal ticket to investigate and solve this issue. We will update you when it is done.

Best Regards,
Can

**Comment by adyen-integrations-support** [comment]
Hey @timkoopmans50 

Please note that our team fixed this issue by changing the type of merchant reference so that it can accept null values. In the case of a null value, the additional log is added.

This fix will be available in the next plugin release.

Best regards.
