### ISSUE TITLE
Date format on potential NULL values in the admincontroller can result in critical error

### ISSUE THREAD

**Issue by timkoopmans50** [Adyen/adyen-shopware6#377]
**Describe the bug**
Sometimes the createdAt and updatedAt colums are NULL. No type test is done in the adminController resulting in a critical error. 

**Versions**
Shopware version: -
Plugin version: 3.10.1 / 3.11

**Expected behavior**
tested values before formatting them here : https://github.com/Adyen/adyen-shopware6/blob/develop/src/Controller/AdminController.php#L421 and here https://github.com/Adyen/adyen-shopware6/blob/develop/src/Controller/AdminController.php#L422

**Comment by candemiralp** [comment]
Hello @timkoopmans50,

Closing this ticket since it is a duplicate of #270. You can check the updates on the first Github issue.

Best Regards,
Can
