### ISSUE TITLE
Shopware 6.4.3.0 - Installation is failing

### ISSUE THREAD

**Issue by joelruizcabrera** [Adyen/adyen-shopware6#386]
After activating Adyen plugin on Shopware 6 it fails and causes this error. Also in the administration panel or via CLI:

![image](https://github.com/Adyen/adyen-shopware6/assets/57678860/c4a763ca-90b2-4ed3-b57d-df3053458fa4)

Does anyone have a theory why this error appears every time and the plugin can not be activated accordingly? We have uploaded the plugin via a .ZIP file. The auth.json was also adjusted accordingly.

**Comment by candemiralp** [comment]
Hello @joelruizcabrera,

Is the issue still reproducible on the latest version of the plugin?

Best Regards,
Can
