### ISSUE TITLE
Support for Shopware 6.5.x ?

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#387]
Any news regarding support for Shopware 6.5.x? According to the composer.json and store.shopware.com it is not supported yet.

**Comment by thrieg** [comment]
I am also eagerly waiting for Shopware 6.5.x support.

It would be great if you could make it possible soon. :)

**Comment by felixgoldstein** [comment]
+1

**Comment by candemiralp** [comment]
Hello all,

Thank you for raising this issue. We are still working on this task to support Shopware 6.5. The new version of the plugin will be released soon with Shopware 6.5 support.

Best Regards,
Can

**Comment by robbelDev** [comment]
Hello,

when is soon reached?

Best Regards

**Comment by candemiralp** [comment]
Hello all,

New version of the plugin with Shopware 6.5 support was released.

Best Regards,
Can
