### ISSUE TITLE
Bizum support?

### ISSUE THREAD

**Issue by YVDJ** [Adyen/adyen-shopware6#393]
We would like to provide the Adyen Bizum payment method in our store.
Is there timeline in which version Bizum is going to be supported?

[https://docs.adyen.com/payment-methods/bizum](https://docs.adyen.com/payment-methods/bizum)

Thanks in advance!

**Comment by logeecom** [comment]
Hey @YVDJ ,

Thank you for suggesting the addition of this payment method. Our team will review the proposal thoroughly and consider its potential implementation in the future. At this time, there is no specific timeline.

Best regards.
