### ISSUE TITLE
Shopware 6.5.2.1 - Installation and activation are failing

### ISSUE THREAD

**Issue by hakimdjabri** [Adyen/adyen-shopware6#403]
**Describe the bug**
 Installation and activation are failing

**Versions**
Shopware version:  6.5.2.1]
Plugin version: [e.g. 3.12.1]
PHP version: 8.2.8

**To Reproduce**
1. Go to 'console CLI'
2.  Run : `composer require store.shopware.com/adyenpaymentshopware6`
3. also when I run : `bin/console plugin:install --activate AdyenPaymentShopware6`
4. See error below  (screenshots) the shop doesn't work after this try to install Adyen plugin

**Expected behavior**

install and activate the plugin

**Screenshots**
**when I run :** `composer require store.shopware.com/adyenpaymentshopware6`

![image](https://github.com/Adyen/adyen-shopware6/assets/47453138/21969cfa-18a2-48da-8f02-026c60a38e16)

**when I run :** `bin/console plugin:install --activate AdyenPaymentShopware6`

![image](https://github.com/Adyen/adyen-shopware6/assets/47453138/5a8e3809-4b82-4be2-a55f-b57db751edc7)

**Comment by hakimdjabri** [comment]
I found the problem and the solution : to install the plugin you should use `composer require adyen/adyen-shopware6` instead of the `composer require store.shopware.com/adyenpaymentshopware6` the plugin should be installed inside 'Vendor/' and not 'store.shopware .com/' directory . but if Adyen can solve the problem that we be able to install the plugin from shopware store with this cmd `composer require store.shopware.com/adyenpaymentshopware6`  it will be nice and helpfull

**Comment by candemiralp** [comment]
Hello @hakimdjabri,

Thanks for creating this issue. Unfortunately, it is a known issue on the given version of the plugin due to incompatibility of the logger. This issue was fixed on the next version.

Best Regards,
Can
