### ISSUE TITLE
[ECP-8840] "origin" is used from "additionalData" instead of the root property.

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#404]
**Describe the bug**
The "origin" parameter set by the web components is set in the root level not the additionalData level, so in most cases this value is ignored. Especially, as CheckoutStateDataValidator removes origin from the default data as well.

For headless implementations where the product URL might not be set, it would be nice if the correct origin is used.
Might even be something that should be changed in the php-api-library, so that CheckoutStateDataValidator does not remove origin, but then the check would still be wrong as you would need to check if it is set in $request.

**Versions**
Shopware version: 6.5.3.3
Plugin version: 3.12.1

**Comment by AndreasA** [comment]
according to https://github.com/Adyen/adyen-php-api-library/issues/536#issuecomment-1735747796 and https://github.com/Adyen/adyen-php-api-library/issues/531#issuecomment-1735749828

that validator should not be used anymore.

**Comment by candemiralp** [comment]
Hello @AndreasA,

Thank you for raising this issue. We've created an investigation ticket. We'll inform you when we finish the investigation.

Best Regards,
Can

**Comment by adyen-integrations-support** [comment]
Hey all,

Please note that our team fixed this issue.

Changes are pushed on:

3.x - fix/develop-3-CS-5934

4.x - fix/CS-5934

branches.

This will be available in the next plugin release.

Best regards.
