### ISSUE TITLE
[ECP-8628] From version 3.12.1 the plugin is no longer compatible with Shopware 6.4.*, although composer.json says "shopware/core": "^6.4.0.0"

### ISSUE THREAD

**Issue by sevarozh** [Adyen/adyen-shopware6#419]
**Describe the bug**
From version 3.12.1 the plugin is no longer compatible with Shopware 6.4.*, although composer.json says "shopware/core": "^6.4.0.0"
see commit: https://github.com/Adyen/adyen-shopware6/commit/e3aa3f8739724f81af1fc5b11b43780e781601b2

This produces TypeError: Adyen\Shopware\Service\ConfigurationService::__construct(): Argument #2 ($mediaRepository) must be of type Shopware\Core\Framework\DataAbstractionLayer\EntityRepository, Shopware\Core\Content\Media\DataAbstractionLayer\MediaRepositoryDecorator given

**Versions**
Shopware version: 6.4.18.1
Plugin version: 3.12.1 - 3.14.0 

**To Reproduce**
1. Shopware 6.4.18.1 clean install
2. Install AdyenPaymentShopware6 v3.12.1
3. Activate Plugin

**Comment by candemiralp** [comment]
Hello @sevarozh,

Thank you for raising this issue and unfortunately it is a known issue on that version. Could you please upgrade to [3.14.0](https://github.com/Adyen/adyen-shopware6/releases/tag/3.14.0)? That version has a consistent version definition in composer.json.

We created an investigation ticket for the type error. You will be informed after the investigation is completed.

Best Regards,
Can
