### ISSUE TITLE
[ECP-8839] CheckoutStateDataValidator is deprecated and should not be used anymore

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#424]
The CheckoutStateDataValidator should not be used anymore according to https://github.com/Adyen/adyen-php-api-library/issues/536#issuecomment-1735747796 and 
https://github.com/Adyen/adyen-php-api-library/issues/531#issuecomment-1735749828

this would also mostly fix https://github.com/Adyen/adyen-shopware6/issues/404 and partly https://github.com/Adyen/adyen-shopware6/issues/210

**Comment by candemiralp** [comment]
Hello @AndreasA,

Thank you for raising this issue. We've create a ticket to implement an alternative.

Best Regards,
Can

**Comment by adyen-integrations-support** [comment]
Hi @AndreasA @candemiralp ,

We wanted to check in regarding the issue you previously reported. Has it been resolved, or do you still require our assistance?

Please let us know if there is anything further we can help with or if we can consider the matter closed.

Kind regards

**Comment by adyen-integrations-support** [comment]
Hi,

Thank you for your fast response.

We’ll go ahead and close this ticket now. If you encounter any further issues or need assistance, please don’t hesitate to create a new ticket.

Best regards
