### ISSUE TITLE
[ECP-8904] Reinstallation flow not working

### ISSUE THREAD

**Issue by wannevancamp** [Adyen/adyen-shopware6#426]
**Describe the bug**
After reinstalling the plugin not all destructive migrations are processed correctly.
The migration `src/Migration/Migration1681716164AlterAdyenPayment.php` will try to alter the table twice. This will result in the following error. The plugin installation can't be completed.

This occurs since plugin version`3.11.0`.

````
[2023-10-12T06:30:13.498646+00:00] app.ERROR: Migration: "Adyen\Shopware\Migration\Migration1681716164AlterAdyenPayment" failed: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'UQ_ADYEN_PAYMENT_PSPREFERENCE'" [] []
````

**Versions**
Shopware version: 6.5.1.1
Plugin version: 3.14.1

**To Reproduce**
1. Install plugin
2. Deinstall plugin
3. Install plugin again
4. Error is thrown

**Expected behavior**
Reinstall plugin without errors

**Comment by hossam-adyen** [comment]
Hi @wannevancamp, thanks for your valuable contribution, we were able to reproduce it, we add it into our backlog and once it got picked and fix, we will update the issue

**Comment by alessandroaussems** [comment]
@hossam-adyen Almost 7 months later... Any update on this?

**Comment by damian-pastorini** [comment]
Still an issue on 4.1.0 and SW 6.6.

**Comment by adyen-integrations-support** [comment]
Hi,

We have successfully reproduced the issue on the latest Shopware 6.5 and Adyen v3 plugin. Our team is currently investigating the root cause to implement a fix.

We will keep you informed as soon as we have more information or updates regarding this ticket. Thank you for your patience and understanding.

Kind regards

**Comment by adyen-integrations-support** [comment]
Hi,

Thank you for your patience while we continue working on this ticket. Our team is actively investigating the issue, and we’ll provide an update as soon as we have more information.

We appreciate your understanding and will keep you informed of our progress.

Best regards

**Comment by adyen-integrations-support** [comment]
Hi,

We want to inform you that we have released new versions of the plugin on Marketplace and on GitHub where this issue has been fixed. You can download it using the following links:

https://store.shopware.com/en/adyen70424242359f/adyen-payments-for-shopware-6.html 

https://github.com/Adyen/adyen-shopware6/releases/tag/3.17.1 

https://github.com/Adyen/adyen-shopware6/releases/tag/4.2.1 

If you have any questions or need further assistance, feel free to reach out.

Best regards
