### ISSUE TITLE
Implement log rotate

### ISSUE THREAD

**Issue by MelvinAchterhuis** [Adyen/adyen-shopware6#437]
**Describe the bug**
Currently the logs are written in a three single log files. This results in large .log files over time and makes debugging harder.

**Versions**
Shopware version: 6.5.7.2
Plugin version: 3.14.1

**To Reproduce**
Install plugin and lots of transactions
After a while you will end up with huge .log files:
<img width="285" alt="image" src="https://github.com/Adyen/adyen-shopware6/assets/26538915/d722079a-e843-43a1-a0c1-e5049dc914ca">

**Expected behavior**
Every day new log file gets created, so

`adyen_api-prod-2023-11-27`
`adyen_notification-prod-2023-11-27`
`adyen_api-prod-2023-11-28`
`adyen_notification-prod-2023-11-28`

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by candemiralp** [comment]
Hello @MelvinAchterhuis,

Thank you for raising this issue and your enhancement idea. 

To be honest, we are on the opposite side of this idea for the following reasons. We believe log rotation is the responsibility of the system admin but not the plugin code. That implementation increases the complexity of the payment plugin and might force our merchants to use a single rotation way which is provided by us. However, we have a lot of merchants that are rotating the logs in different ways.

Most commonly used tool by system admins is [logrotate](https://linux.die.net/man/8/logrotate). You can install and configure this tool to manage and rotate your logs.

Best Regards,
Can
