### ISSUE TITLE
[ECP-8915] AbstractPaymentMethodHandler NullPointer Exception for Products without Category/Categories

### ISSUE THREAD

**Issue by thomaswiener** [Adyen/adyen-shopware6#450]
Error Report for
store.shopware.com/adyenpaymentshopware6:^3.13
file: store.shopware.com/adyenpaymentshopware6/src/Handlers/AbstractPaymentMethodHandler.php:663
Is:
```
if (isset($product) && !is_null($product->getCategories())) {
    $productCategory = $product->getCategories()->first()->getName();
} else {
    $productCategory = null;
}
```
Should:
```
if (isset($product) && !is_null($product->getCategories()) && $product->getCategories()->count() > 0) {
    $productCategory = $product->getCategories()->first()->getName();
} else {
    $productCategory = null;
}
```
Why:
product->getCategories() is a collection but might have no items. Unlike an empty array which is consider null, a collection without items is not null. This leads to an error on the next line, when the first item of an empty collection is taken (in this case null) and throws an php exception when trying to get getName() on null. (

**Comment by hossam-adyen** [comment]
Hi @thomaswiener , thanks for your valuable report, I've opened a PR for that fix and once it's reviewed and merged it will be included in the next release
