### ISSUE TITLE
OFFER_CLOSED webhooks does not change payment state

### ISSUE THREAD

**Issue by wannevancamp** [Adyen/adyen-shopware6#486]
**Describe the bug**
Webhooks with eventCode `OFFER_CLOSED` are not processed. The payment status should automatically be changed to `failed`.
No $orderTransaction are found.

```
$orderTransaction = $this->getOrderTransaction($order, $notification, $logContext);
    if (is_null($orderTransaction)) {
        continue;
    }
```

**Versions**
Shopware version: all
Plugin version: all

**To Reproduce**
1. Create an order but do not pay
2. Shopware receives a webhook from Adyen with `OFFER_CLOSED`
3. Plugin tries to process webhook but skips `OFFER_CLOSED` webhooks.
4. Payment status stays in `in progress`

**Expected behavior**
 Payment status must be update to `failed`

**Comment by RokPopov** [comment]
Hi @wannevancamp,

Thank you for reporting this issue. May I ask, what version of our plugin and the Shopware6 platform are you experiencing this issue with?

Kind regards,
Rok

**Comment by wannevancamp** [comment]
Hi @RokPopov , I've tested this on 3.14.4. But as far as I can see this issue will occur with every version

**Comment by wannevancamp** [comment]
This seems to related to https://github.com/Adyen/adyen-shopware6/issues/310

**Comment by RokPopov** [comment]
Thank you @wannevancamp and apologies for the delay in my reply. Indeed, the support for OFFER_CLOSED notifications was added in [PW-7480](https://github.com/Adyen/adyen-shopware6/pull/324). I am closing this issue as of now.

Cheers,
Rok
