### ISSUE TITLE
[PW-2842] Install with composer fails due to missing/not required autoload.php

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#49]
**Describe the bug**

If trying to install the plugin using the project's composer there is an error upon activating / refreshing the plugin list as it tries to require a missing `autoload.php` which is not necessary as the dependencies are already loaded by the project's main `autoload.php`.

**To Reproduce**
Add 
```
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/Adyen/adyen-shopware6.git"
        }
    ],
```

to the project's `composer.json`.

Execute: `composer require "adyen/adyen-shopware6:dev-develop"`

Execute 
```
bin/console plugin:refresh
bin/console plugin:install --clearCache --activate AdyenPaymentShopware6
```

**Expected behavior**
In the file for `\Adyen\Shopware\AdyenPaymentShopware6` the `require_once __DIR__ . '/../vendor/autoload.php';` should only be done, if not installed by composer. Probably the easiest way is to only require the file if it exists.

**Comment by AndreasA** [comment]
Furthermore, `\Adyen\Shopware\Service\ClientService::getModuleVersion` tries to load the `composer.json` from the `plugins` folder. However, that does not include other folders like the vendor folder or `custom/static-plugins` which is defined by default in production template https://github.com/shopware/production

**Comment by acampos1916** [comment]
Thanks for this feedback @AndreasA, we have moved this issue to our internal tracker and we'll update you with any progress made.

Cheers,
Ángel
