### ISSUE TITLE
Shopware 6.6 compatibility

### ISSUE THREAD

**Issue by wannevancamp** [Adyen/adyen-shopware6#511]
Hi Adyen,

When can we expect compatibility for Shopware 6.6?

Kind regards,
Wanne

**Comment by hakimdjabri** [comment]
Hi Adyen Team,

We start to migrate our webshop to shopware 6.6.3 but we are waiting your update 

Please, When we can use Adyen plugin with Shopware 6.6.* ?

Kind regards,
Hakim DJABRI
