### ISSUE TITLE
Js error on Symfony Prod mode because of moved inline JS

### ISSUE THREAD

**Issue by Gugiman** [Adyen/adyen-shopware6#538]
**Describe the bug**
If you change from dev to Production mode in .env, the inline JS moved to the head of the DOM.
This symfony default behaviour:
https://symfony.com/blog/moving-script-inside-head-and-the-defer-attribute#the-caveat-inline-javascript-cannot-be-deferred

Therefore no customer can checkout correctly.

**Versions**
Shopware version: 6.5.8.13
Plugin version: 3.15.0

**To Reproduce**
1. Setup a running Adyen implementation with Paypal and credit card in Shopware dev mode
2. Verify that the Credit Card Field are loaded on checkout/confirm
3. Switch from dev to prod in .env and clear all caches
4. Reload Page and see a js console error because 
`document.querySelector('#adyen-checkout-options').dataset` is called and executed in the head before the `<div id="adyen-checkout-options">` exists.

**Expected behavior**
Inline JS should be called after the DOM is completely rendered by the Browser or the <script> tags have to have the attribute "defer"

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser Chromium
 - Version 127.0.6533.72

**Comment by adyen-integrations-support** [comment]
Hey @Gugiman,

Thank you for providing the details about the issue. Our team followed the steps you shared and confirmed that the issue could not be reproduced on the latest version of the plugin (v3.16.3).

Could you please update to the latest version and let us know if the issue persists?

We look forward to your feedback.

Best regards.
