### ISSUE TITLE
shopware store version vs. composer installation

### ISSUE THREAD

**Issue by 0x4** [Adyen/adyen-shopware6#571]
If the plugin is installed via composer with the shopware-store url

```
composer require store.shopware.com/adyenpaymentshopware6 
```

then the plugin is listed 2 times in the plugin:list command 

```
Shopware Plugin Service
=======================

 -------------------------------------- ------------------------------------------ --------------------------------------------------------- --------- ----------------- ----------------------- ----------- -------- ------------- ----------------------
  Plugin                                 Label                                      Composer name                                             Version   Upgrade version   Author                  Installed   Active   Upgradeable   Required by composer
 -------------------------------------- ------------------------------------------ --------------------------------------------------------- --------- ----------------- ----------------------- ----------- -------- ------------- ----------------------
  AdyenPaymentShopware6                  Adyen Payment                              store.shopware.com/adyenpaymentshopware6                  4.1.3                       Adyen                   Yes         Yes      No            Yes
... 
 AdyenPaymentShopware6                                                                                                                       4.1.3                                               No          No                     Yes
```

Seems that this is not causing any problems, but looks wrong...
I think the problem is, that the composer version contains a vendor directory with a composer/installed.php file and composer loads this too

**Versions**
Shopware version: 6.6.7.0
Plugin version: 4.1.3

**To Reproduce**
Install the plugin via composer

**Expected behavior**
plugin:list shows the adyen plugin only once

**Comment by adyen-integrations-support** [comment]
Hello @0x4,

Thank you for reaching out to us regarding this issue,

Please note that we attempted to reproduce the reported issue in a local environment but we were unsuccessful.
![image](https://github.com/user-attachments/assets/76f58553-a34b-43ce-90b9-f7c6f3214f43)
After executing **bin/console plugin:list** command, the plugin is listed only once, as evidenced by the screenshot above. We tried with PHP8.2 and 8.3 but the result was the same.

Could it be possible that you previously installed the Adyen plugin via zip, uninstalled it, and then installed the Adyen plugin with composer?

Could you try to reproduce the issue on your end again and let us know if you can do so?

Thank you,

Kind regards.

**Comment by adyen-integrations-support** [comment]
Hello @0x4,

Thank you for the feedback.

Note that our team was able to reproduce the issue after running plugin:refresh command after the installation.

Our team will proceed with fixing the issue.

We will let you know as soon as we have some valid information to share.

Kind regards.

**Comment by adyen-integrations-support** [comment]
Hello @0x4,

Please note that our team is still working on this issue.

As soon as we have some valid information to share, we will let you know.

Thank you,

Kind regards.
