### ISSUE TITLE
paypal payment status inconsistent after client aborts

### ISSUE THREAD

**Issue by 0x4** [Adyen/adyen-shopware6#576]
Paypal-via-Adyen: If a customer checks out via Paypal and closes the paypal window or aborts the paypal process from the paypal window, the confirmorder JS plugin will trigger vie CancelOrderTransactionURL an XHR POST  /adyen/proxy-cancel-order-transaction . this is obviously meant to reset the payment status of the order to "aborted". This call is often blocked/cut off by the client.
This leads to a race condition. If the call "goes through" and reaches the server, the payment status of the order will be reset to "aborted" and everything is fine going forwad.
If the call "does not go though" this will lead to the order sticking in payment status "in progress" which in turn will lead to /account/order/edit/<id>?error-code-CHECKOUT__UNKOWN_ERROR to fail with an error message because the order is payment "in progress" which will block changing the payment method (and retrying), such blocking the user:

to reproduce:
* Create an order
* start checkout with paypal
* close paypal window
* check for 2 error messages in /account/order/edit
* if only one appears: retry paying and aborting until 2 error messages appear (with our setup about 30% of the time)

Shopware version: 6.5.8.13
Plugin version: 3.15.0

Looks like this could be the bug fixed in 4.1.3 as there is an entry: "Fix blocked checkout after PayPal payment cancellation" - if it's so any chance to port this to 3.x? We cannot update to 4.x currently because we are not on shopware 6.6

**Comment by adyen-integrations-support** [comment]
Hi,

Thank you for your patience. We wanted to let you know that we are actively looking into your ticket. We will contact you as soon as we have more information or updates to share.

If you have any additional details in the meantime, feel free to reach out.

Best regards

**Comment by teodoratimoti** [comment]
Hi @0x4 ,

We have identified and resolved the issue with the front-end handling of PayPal transaction cancellations. The fix will be included in the next plugin release.

We will inform you as soon as the update is available for download. Should you have any questions in the meantime, feel free to reach out.

Best regards

**Comment by adyen-integrations-support** [comment]
Hi @0x4 ,

We have identified and resolved the issue with the front-end handling of PayPal transaction cancellations. The fix will be included in the next plugin release.

We will inform you as soon as the update is available for download. Should you have any questions in the meantime, feel free to reach out.

Best regards

**Comment by adyen-integrations-support** [comment]
Hi @0x4 ,

We want to inform you that we have released new versions of the Adyen plugin with a fix for the issue you described.

You can download the new version from the Shopware Store or your Adyen account and proceed with the update.

V3:
https://github.com/Adyen/adyen-shopware6/releases/tag/3.17.3


V4:
https://github.com/Adyen/adyen-shopware6/releases/tag/4.2.2 

https://store.shopware.com/en/adyen70424242359f/adyen-payments-for-shopware-6.html?srsltid=AfmBOoq1FKKeICTjydlcChkAgACz5D4TTLOilVmY9dHREpzSV5UzX8ld

If you encounter any further issues or have additional questions, please don’t hesitate to reach out.

Best regards
