### ISSUE TITLE
3.17.2 release requires Shopware 6.6 and uses version 4.2.2 in composer.json?

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#591]
**Describe the bug**
See https://github.com/Adyen/adyen-shopware6/blob/3.17.2/composer.json

According to the composer.json of 3.17.2 it requires Shopware 6.6 and the version number of the plugin is 4.2.2.

**Versions**
Shopware version: 6.5.8.14
Plugin version: 3.17.2

**Comment by AndreasA** [comment]
Also 3.17.1 even supported Shopware 6.4 which means it should support php 7.4 as well and the current code changes do not support php 7.4 either e.g. it uses the null safe operator or property types.

**Comment by adyen-integrations-support** [comment]
Hi @AndreasA ,

Thank you for bringing this to our attention. Version 3.17.2 was mistakenly released with these requirements. To address this, we have released a new version, 3.17.3, where this issue has been fixed.

https://github.com/Adyen/adyen-shopware6/releases/tag/3.17.3

Please update to the version 3.17.3, which is now available. Please let us know if you encounter any further issues.

Best regards
