### ISSUE TITLE
[PW-3354] Iframe + loadbalancer

### ISSUE THREAD

**Issue by TaiKamilla** [Adyen/adyen-shopware6#74]
If the server is behind a loadbalancer there will be an Iframe issue because of the originKey

![image](https://user-images.githubusercontent.com/15035750/96134429-8cfe7a80-0efb-11eb-801c-4a865fe26f6a.png)

**Comment by acampos1916** [comment]
Hi @TaiKamilla,

Looks like the origin keys generated do not match the domain where the iframe is trying to be rendered. Could you check the api.log to see the originKeys request and which domain did it use? You’ll find it with the following request URL for test: https://checkout-test.adyen.com/checkout/v1/originKeys

The load balancer can be the problem indeed. We fetch the domain from the sales channel configuration in the admin, so maybe it is set to use the HTTP protocol there and not HTTPS, which could happen if the load balancer is responsible for SSL termination. The first domain for the sales channel should match the one where the iframe will be rendered.

**Comment by acampos1916** [comment]
#93 implements client key authentication, which allows for defining multiple domains in Customer Area. Docs will be published here https://docs.adyen.com/plugins/shopware-6#generate-a-client-key
