### ISSUE TITLE
[PW-3621] Custom fields for e.g. transaction ID not stored?

### ISSUE THREAD

**Issue by AndreasA** [Adyen/adyen-shopware6#92]
**Describe the bug**
It appears the custom fields like PSP transaction ID are not stored on the order transaction.
Not sure, if that is by design.

**Expected behavior**
Store custom fields on order transaction.
Also way not store the current PSP reference ID too. why only the original?

**Additional context**

You execute: `$transaction->getOrderTransaction()->setCustomFields($customFields);`
However, the Shopware DAL is not an ORM and therefore this does not store the fields at all. You just set it in the order transaction object.

In order to store custom data on the order transaction you need to do something like this:
```php
        $context->scope(
            Context::SYSTEM_SCOPE,
            function (Context $context) use ($transaction, $customFields): void {
                   $this->orderTransactionRepository->update(
            [
                [
                    'id' => $transaction->getId(),
                    // Shopware uses JSON SQL functions to update only provided fields.
                    'customFields' => $cusotmFields,
                ],
            ],
            $context,
        );
            },
        );
```

**Comment by acampos1916** [comment]
Thanks for opening this issue @AndreasA,

I've created an internal ticket to work on it. Your snippet will be useful!

Best,
Ángel

**Comment by AndreasA** [comment]
The system scope is most likely necessary as I think you cannot update orders directly otherwise but you can try without it too.
